/*******************************************************************************
* File Name: cyfitter_sysint.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_H
#define INCLUDED_CYFITTER_SYSINT_H
#include "cy_device_headers.h"

/* CapSense_ISR */
#define CapSense_ISR__INTC_CORTEXM4_ASSIGNED 1
#define CapSense_ISR__INTC_CORTEXM4_PRIORITY 7u
#define CapSense_ISR__INTC_NUMBER 49u
#define CapSense_ISR_INTC_CORTEXM4_ASSIGNED 1
#define CapSense_ISR_INTC_CORTEXM4_PRIORITY 7u
#define CapSense_ISR_INTC_NUMBER 49u

/* I2Cm_SCB_IRQ */
#define I2Cm_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define I2Cm_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define I2Cm_SCB_IRQ__INTC_NUMBER 44u
#define I2Cm_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define I2Cm_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define I2Cm_SCB_IRQ_INTC_NUMBER 44u

/* I2C_MAX_SCB_IRQ */
#define I2C_MAX_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define I2C_MAX_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define I2C_MAX_SCB_IRQ__INTC_NUMBER 43u
#define I2C_MAX_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define I2C_MAX_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define I2C_MAX_SCB_IRQ_INTC_NUMBER 43u

/* SysInt_OrientINT */
#define SysInt_OrientINT__INTC_CORTEXM4_ASSIGNED 1
#define SysInt_OrientINT__INTC_CORTEXM4_PRIORITY 7u
#define SysInt_OrientINT__INTC_NUMBER 122u
#define SysInt_OrientINT_INTC_CORTEXM4_ASSIGNED 1
#define SysInt_OrientINT_INTC_CORTEXM4_PRIORITY 7u
#define SysInt_OrientINT_INTC_NUMBER 122u

/* CY_EINK_SPIM_SCB_IRQ */
#define CY_EINK_SPIM_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define CY_EINK_SPIM_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define CY_EINK_SPIM_SCB_IRQ__INTC_NUMBER 47u
#define CY_EINK_SPIM_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define CY_EINK_SPIM_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define CY_EINK_SPIM_SCB_IRQ_INTC_NUMBER 47u

#endif /* INCLUDED_CYFITTER_SYSINT_H */
